#!/bin/sh
# Copyright (c) Kelly Harnden
# ugly needs to do some first boot stuff
# note: this is currently not totally needed
# as we could just fire this stuff off in the
# suse studio build script first boot section
# but is not disruptive in testing and will
# probably be needed soon.

case "$1" in
  start)
        /opt/uglybits/sbin/ugly-pommed-install 
	insserv /etc/init.d/ugly-first-boot -r
        ;;
  stop)
        echo "I'm Done"
        ;;
  restart)
        echo "Restarts are ignored"
        ;;
  reload|force-reload)
        echo "Reloads are ignored"
        ;;
  status)
        echo "Status checks are ignored"
        ;;
  *)
        echo "You are doing it wrong"
        exit 1
        ;;
esac
 
exit
