#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "~/.Xmodmap"
synclient TapButton1=0 TapButton2=0 TapButton3=0
# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
gkrellm -w &
xterm -rv &
blueman-applet &
fbsetbg ~/.fluxbox/backgrounds/spaceshuttlewallpaper.jpg &
# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "~/.fluxbox/log"
